const dataInfo = `
  [
    {
      "idDrink":"11007",
      "strDrink":"Margarita",
      "strDrinkAlternate":null,
      "strDrinkZH-HANS":null,
      "strDrinkZH-HANT":null,
      "strTags":"IBA,ContemporaryClassic",
      "strVideo":null,
      "strCategory":"Ordinary Drink",
      "strIBA":"Contemporary Classics",
      "strAlcoholic":"Alcoholic",
      "strGlass":"Cocktail glass",
      "strInstructions":"Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
      "strInstructionsZH-HANS":null,
      "strInstructionsZH-HANT":null,
      "strDrinkThumb":"https://www.thecocktaildb.com//images//media//drink//wpxpvu1439905379.jpg",
      "strCreativeCommonsConfirmed":"No",
      "dateModified":"2015-08-18 14:42:59"
    },
    {
      "idDrink":"11118",
      "strDrink":"Blue Margarita",
      "strDrinkAlternate":null,
      "strDrinkZH-HANS":null,
      "strDrinkZH-HANT":null,
      "strTags":null,
      "strVideo":null,
      "strCategory":"Ordinary Drink",
      "strIBA":null,
      "strAlcoholic":"Alcoholic",
      "strGlass":"Cocktail glass",
      "strInstructions":"Rub rim of cocktail glass with lime juice. Dip rim in coarse salt. Shake tequila, blue curacao, and lime juice with ice, strain into the salt-rimmed glass, and serve.",
      "strInstructionsZH-HANS":null,
      "strInstructionsZH-HANT":null,
      "strDrinkThumb":"https://www.thecocktaildb.com//images//media//drink//qtvvyq1439905913.jpg",
      "strCreativeCommonsConfirmed":"No",
      "dateModified":"2015-08-18 14:51:53"
    },
    {
      "idDrink":"17216",
      "strDrink":"Tommy's Margarita",
      "strDrinkAlternate":null,
      "strDrinkZH-HANS":null,
      "strDrinkZH-HANT":null,
      "strTags":"IBA,NewEra",
      "strVideo":null,
      "strCategory":"Ordinary Drink",
      "strIBA":"New Era Drinks",
      "strAlcoholic":"Alcoholic",
      "strGlass":"Old-Fashioned glass",
      "strInstructions":"Shake and strain into a chilled cocktail glass.",
      "strInstructionsZH-HANS":null,
      "strInstructionsZH-HANT":null,
      "strDrinkThumb":"https://www.thecocktaildb.com//images//media//drink//loezxn1504373874.jpg",
      "strCreativeCommonsConfirmed":"No",
      "dateModified":"2017-09-02 18:37:54"
    },
    {
      "idDrink":"16158",
    "strDrink":"Whitecap Margarita",
    "strDrinkAlternate":null,
    "strDrinkZH-HANS":null,
    "strDrinkZH-HANT":null,
    "strTags":null,
    "strVideo":null,
    "strCategory":"Other\/Unknown",
    "strIBA":null,
    "strAlcoholic":"Alcoholic",
    "strGlass":"Margarita\/Coupette glass",
    "strInstructions":"Place all ingredients in a blender and blend until smooth. This makes one drink.",
    "strInstructionsZH-HANS":null,
    "strInstructionsZH-HANT":null,
    "strDrinkThumb":"https://www.thecocktaildb.com//images//media//drink//srpxxp1441209622.jpg",
    "strCreativeCommonsConfirmed":"No",
    "dateModified":"2015-09-02 17:00:22"
  },
  {
    "idDrink":"12322",
    "strDrink":"Strawberry Margarita",
    "strDrinkAlternate":null,
    "strDrinkZH-HANS":null,
    "strDrinkZH-HANT":null,
    "strTags":null,
    "strVideo":null,
    "strCategory":"Ordinary Drink",
    "strIBA":null,
    "strAlcoholic":"Alcoholic",
    "strGlass":"Cocktail glass",
    "strInstructions":"Rub rim of cocktail glass with lemon juice and dip rim in salt. Shake schnapps, tequila, triple sec, lemon juice, and strawberries with ice, strain into the salt-rimmed glass, and serve.",
    "strInstructionsZH-HANS":null,
    "strInstructionsZH-HANT":null,
    "strDrinkThumb":"https://www.thecocktaildb.com//images//media//drink//tqyrpw1439905311.jpg",
    "strCreativeCommonsConfirmed":"No",
    "dateModified":"2015-08-18 14:41:51"
  }
  ]
`